# Generated by Django 4.2.1 on 2023-05-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Curso',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='birth_date',
            new_name='data_nascimento',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='course_code',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='level',
            new_name='nivel',
        ),
    ]
